### PR TITLE
Feature/settings

### PR DESCRIPTION
**Pull request by Mutinda-Kioko**
Settings

### CODE REVIEW

**Review by steffenkrogmann — COMMENTED** [review]
@Mutinda-Kioko 
@Alphonce-Mutebi @Allen-Muhani 

Why are there so many changes to the colors.tx file in this PR?
Shouldn't that file have been basically done?

**Comment by Mutinda-Kioko** [comment]
> @Mutinda-Kioko @Alphonce-Mutebi @Allen-Muhani
> 
> Why are there so many changes to the colors.tx file in this PR? Shouldn't that file have been basically done?

I added the textColor4, dividerLine and switchThumb because there were not there as indicated in the figma design(I didn't get any defined colors with the same hex codes)

**Comment by steffenkrogmann** [comment]
@Mutinda-Kioko please always tag names when commenting so the right person always gets notified.

@Chegemartinx can you discuss with @Mutinda-Kioko the color issue?

@Mutinda-Kioko if something is missing , please make sure to also sync back with @Chegemartinx 
because e.g. the colors file in the codebase should match the colors list in figma.

**Comment by Mutinda-Kioko** [comment]
Thanks alot @steffenkrogmann , we discussed the issues during yesterday's stand up and @Allen-Muhani said he would look into it and suggest a solution once he looks at the pr...

**Comment by steffenkrogmann** [comment]
@Alphonce-Mutebi i don't quite understand what is going on in the colors file.
there seem to be 55 changes.
@Mutinda-Kioko only meant to change 3 lines. can you look into that?

**Comment by steffenkrogmann** [comment]
@Allen-Muhani @Alphonce-Mutebi it seems like @Mutinda-Kioko code got flagged as changed (new, green, red, etc), but he says he did not change it.

is there some conflict? did he pull a wrong branch?

**Comment by Mutinda-Kioko** [comment]
@steffenkrogmann , @Alphonce-Mutebi , @Allen-Muhani , @vkamunya  I have updated the color.ts files so it includes only three changes....

**Review by Alphonce-Mutebi — APPROVED** [review]
neat✨

**Review by steffenkrogmann — APPROVED** [review]

**Pull request merged**
