### PR TITLE
Created the Select Currency Screen

### PR DESCRIPTION
**Pull request by Mutinda-Kioko**
Screenshot_20220412-181717_Expo Go

### CODE REVIEW

**Comment by steffenkrogmann** [comment]
@Mutinda-Kioko even though this PR is closed.... the size seems off from what I can see from the screenshot.
Probably the same issue as with the Settings page.

**Comment by Mutinda-Kioko** [comment]
> @Mutinda-Kioko even though this PR is closed.... the size seems off from what I can see from the screenshot.
> Probably the same issue as with the Settings page.

I have followed the font sizes as indicated in the design , I didn't want to tweak them because they are all defined in the Fonts folder....

**Comment by steffenkrogmann** [comment]
@Chegemartinx @Allen-Muhani @Allen-Muhani @Mutinda-Kioko 
Something is wrong here.

@Mutinda-Kioko which font sizes did you use? or which styles? can you post them here?
The height of each menu items also seems off.

There is certainly a difference between the settings page and the main menu.

@Chegemartinx which one is off?

**Comment by Chegemartinx** [comment]
@steffenkrogmann @Mutinda-Kioko the space between the lines is slightly bigger. Similar with the settings page.

**Comment by steffenkrogmann** [comment]
@Mutinda-Kioko that is a bug ;-)

@Chegemartinx  what about the font sizes? Pls compare both Menus

**Comment by Mutinda-Kioko** [comment]
> @steffenkrogmann @Mutinda-Kioko the space between the lines is slightly bigger. Similar with the settings page.

Okay....lemme rectify that ....

**Comment by Mutinda-Kioko** [comment]
> @Mutinda-Kioko that is a bug ;-)
> 
> @Chegemartinx  what about the font sizes? Pls compare both Menus

I will look into them all....

**Comment by Chegemartinx** [comment]
@steffenkrogmann font size seems okay. Also I think the currency page is in all CAPS unlike the settings page which  likely might create a different feel in terms of size. @Mutinda-Kioko Whats font sizes are you using for these two pages (settings and currency page) ?

**Comment by Mutinda-Kioko** [comment]
> @steffenkrogmann font size seems okay. Also I think the currency page is in all CAPS unlike the settings page which  likely might create a different feel in terms of size. @Mutinda-Kioko Whats font sizes are you using for these two pages (settings and currency page) ?

They are both body3 for the titles and body1 for the texts .....as in the designs...

**Comment by Mutinda-Kioko** [comment]
> > @steffenkrogmann font size seems okay. Also I think the currency page is in all CAPS unlike the settings page which  likely might create a different feel in terms of size. @Mutinda-Kioko Whats font sizes are you using for these two pages (settings and currency page) ?
> 
> They are both body3 for the titles and body1 for the texts .....as in the designs...

I looked into the sizes from the designs @Chegemartinx

**Comment by Chegemartinx** [comment]
@Mutinda-Kioko that's correct. Fonts match. Must be the line spacing

**Comment by Mutinda-Kioko** [comment]
> @Mutinda-Kioko that's correct. Fonts match. Must be the line spacing

Okay...lemme correct all that....

**Comment by Chegemartinx** [comment]
@Mutinda-Kioko What font size do you have on your side menu page?

**Comment by steffenkrogmann** [comment]
The font sizes are definitely off @Chegemartinx @Mutinda-Kioko 

It should jump right at you when you open Expo. 
It is NOT just the line spacing.

image


image

**Comment by Mutinda-Kioko** [comment]
> The font sizes are definitely off @Chegemartinx @Mutinda-Kioko 
> 
> It should jump right at you when you open Expo. 
> It is NOT just the line spacing.
> 
> image
> 
> 
> image
> 
> 

Lemme check what the other screens are using....

**Pull request closed without merging**
