### PR TITLE
The enter pin screen....

### PR DESCRIPTION
**Pull request by Mutinda-Kioko**
Pin On type:

Screenshot_20220414-180206_Expo Go
Pin On Error:
Screenshot_20220414-180740_Expo Go

### CODE REVIEW

**Review by Allen-Muhani — APPROVED** [review]

**Comment by steffenkrogmann** [comment]
@Mutinda-Kioko 

when i look at the screenshot only, the dot in the bottom left does not belong there. a PIN cannot have a dot/separator

**Comment by steffenkrogmann** [comment]
image

**Comment by Mutinda-Kioko** [comment]
> @Mutinda-Kioko 
> 
> when i look at the screenshot only, the dot in the bottom left does not belong there. a PIN cannot have a dot/separator

Okay....lemme eliminate it....

**Comment by Alphonce-Mutebi** [comment]
hey @Mutinda-Kioko  please fix conflicts

**Comment by Mutinda-Kioko** [comment]
> @Mutinda-Kioko 
> 
> when i look at the screenshot only, the dot in the bottom left does not belong there. a PIN cannot have a dot/separator

@steffenkrogmann The dot is a dummy key to make the styling consistent,  it's not pressable.....

**Comment by steffenkrogmann** [comment]
@Mutind-Kioko

is the dot in the design?

No ;-)

Stick to the design, don't get creative. Design is the source of truth. 
In cases where you think the design should be different, you should pick it up with @Chegemartinx (design) and the PM (me or @ClaireLagat).

For this specific one:
I appreciate that you care about consistency. but this is simply a different num pad. it is not the same as aentering a currency.

A button/dot that does not do anything is bad UX. so please delete it, as per the design.

**Comment by Mutinda-Kioko** [comment]
> @Mutind-Kioko
> 
> is the dot in the design?
> 
> No ;-)
> 
> Stick to the design, don't get creative. Design is the source of truth. In cases where you think the design should be different, you should pick it up with @Chegemartinx (design) and the PM (me or @ClaireLagat).
> 
> For this specific one: I appreciate that you care about consistency. but this is simply a different num pad. it is not the same as aentering a currency.
> 
> A button/dot that does not do anything is bad UX. so please delete it, as per the design.

I get now....Fixed...
Screenshot_20220420-122542_Expo Go

**Review by Alphonce-Mutebi — APPROVED** [review]

**Pull request merged**
